"""Event type constants for the immutable event journal."""

# Agent lifecycle
AGENT_SPAWNED = "agent.spawned"
AGENT_THOUGHT = "agent.thought"
AGENT_TOOL_CALL = "agent.tool_call"
AGENT_TOOL_ERROR = "agent.tool_error"
AGENT_SPAWN_DECISION = "agent.spawn_decision"
AGENT_BLACKBOARD_WRITE = "agent.blackboard_write"
AGENT_BLACKBOARD_READ = "agent.blackboard_read"
AGENT_OUTPUT = "agent.output"
AGENT_HIBERNATED = "agent.hibernated"
AGENT_RESURRECTED = "agent.resurrected"
AGENT_DIED = "agent.died"
AGENT_COST = "agent.cost"
AGENT_TTL_EXTENDED = "agent.ttl_extended"
